kind: Service
apiVersion: v1
metadata:
 name: nginx  
spec: 
  type: {{ .Values.service.type }}  
  selector:
    tier: frontend
    app: nginx 
  ports:
    - name: nginx-service-port
      protocol: TCP
      port: {{ .Values.service.port }}  #service port
      targetPort: 80 #container port 