kind: Service
apiVersion: v1
metadata:
 name: frontend
 namespace: expense1 
spec: 
  type: LoadBalancer 
  selector:
    app: frontend
    tier: web
    project: expense 
  ports:
    - name: frontend-port
      protocol: TCP
      port: 80  #service port
      targetPort: 80 #container port 